apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: family-agile
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - externalsecret.yaml
  - configmap.yaml
  - cronjob-pull-completions.yaml
  - cronjob-reconcile.yaml
  - cronjob-push-definitions.yaml
  - cronjob-close-cycle.yaml
