apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forge-site
  namespace: forge-demo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - localpower.diegobarahona.com
      secretName: forge-site-tls
  rules:
    - host: localpower.diegobarahona.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forge-site
                port:
                  number: 80
